apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-node-exporter.fullname" . }}
  labels:
    {{- include "nginx-node-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-node-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-node-exporter.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: node-exporter
          image: "{{ .Values.nodeExporter.image.repository }}:{{ .Values.nodeExporter.image.tag }}"
          imagePullPolicy: {{ .Values.nodeExporter.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: 9100
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}