apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30200
  selector:
    app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
spec:
  type: NodePort
  ports:
  - port: 9100
    targetPort: 9100
    nodePort: 30100
  selector:
    app: node-exporter
