apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    nginx-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    nginx
---
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
spec:
  type: NodePort
  ports:
  - port: 9100
    targetPort: 9100
    nodePort: 30100
  selector:
    app: node-exporter
